name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile_test
      run: gcc teste_potencia.c -o test_potencia

    - name: compile
      run: gcc potencia.c -o potencia
      
    - name: execute_test
      run: ./test_potencia

    - name: execute
      run: ./potencia
      
    - name: mostrar o conteúdo do arquivo criado
      run: cat potencia.txt
